### ISSUE TITLE
Expected to find a manifest file in `app/assets/config/manifest.js` 

### ISSUE THREAD

**Issue by kbariotis** [adyen-examples/adyen-rails-online-payments#40]
I was getting this error below when was trying to start the server:

```
➜  adyen-rails-online-payments git:(main) ✗ bundle exec rails s

=> Booting Puma
=> Rails 7.0.3.1 application starting in development
=> Run `bin/rails server --help` for more startup options
Exiting
bundler: failed to load command: rails (/Users/konstantinosbariotis/projects/adyen-rails-online-payments/bin/rails)
/Users/konstantinosbariotis/projects/adyen-rails-online-payments/gems/sprockets-rails-3.4.2/lib/sprockets/railtie.rb:110:in `block in <class:Railtie>': Expected to find a manifest file in `app/assets/config/manifest.js` (Sprockets::Railtie::ManifestNeededError)
But did not, please create this file and use it to link any assets that need
to be rendered by your app:

Example:
  //= link_tree ../images
  //= link_directory ../javascripts .js
  //= link_directory ../stylesheets .css
and restart your server

For more information see: https://github.com/rails/sprockets/blob/070fc01947c111d35bb4c836e9bb71962a8e0595/UPGRADING.md#manifestjs
	from /Users/konstantinosbariotis/projects/adyen-rails-online-payments/gems/railties-7.0.3.1/lib/rails/initializable.rb:32:in `instance_exec'
...
...
...
```

[and I managed to fix it by using this answer from SO](https://stackoverflow.com/a/58370129/1955940)

**Comment by jlengrand** [comment]
I can reproduce, thanks for reporting, let me dive into it!
